#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────────────
#  Shadow Trust SOC Honeynet — One-Click Setup
#  Usage: ./setup.sh
#
#  What it does
#    1. Checks Docker & Docker Compose are installed and running
#    2. Detects your OS and sets the correct MobSF Docker host
#    3. Creates .env files from .env.example templates (skips if already present)
#    4. Touches SQLite database files so Docker bind-mounts work correctly
#    5. Creates required data directories
#    6. Builds all images and starts the stack in detached mode
#    7. Prints service URLs
# ──────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ── Colours ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

step()  { echo -e "\n${YELLOW}${BOLD}[$1/$TOTAL] $2${NC}"; }
ok()    { echo -e "  ${GREEN}✓${NC} $1"; }
warn()  { echo -e "  ${YELLOW}⚠${NC}  $1"; }
fail()  { echo -e "  ${RED}✗${NC} $1"; }
TOTAL=6

banner() {
  echo -e "${CYAN}"
  echo "  ╔══════════════════════════════════════════════════╗"
  echo "  ║   Shadow Trust · Shadow Trust SOC Honeynet       ║"
  echo "  ║   AI-Powered Threat Intelligence Platform         ║"
  echo "  ║   One-Click Docker Setup                          ║"
  echo "  ╚══════════════════════════════════════════════════╝"
  echo -e "${NC}"
}

# ── Step 1 — Prerequisites ────────────────────────────────────────────────────
check_deps() {
  step 1 "Checking prerequisites..."

  if ! command -v docker &>/dev/null; then
    fail "Docker is not installed."
    echo "    Install from: https://docs.docker.com/get-docker/"
    exit 1
  fi

  if ! docker info &>/dev/null 2>&1; then
    fail "Docker daemon is not running. Please start Docker Desktop and retry."
    exit 1
  fi

  # Prefer Compose v2 plugin; fall back to standalone v1
  if docker compose version &>/dev/null 2>&1; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
  else
    fail "Docker Compose not found."
    echo "    Install from: https://docs.docker.com/compose/install/"
    exit 1
  fi

  ok "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
  ok "Compose ($COMPOSE_CMD)"
}

# ── Step 2 — Platform detection ───────────────────────────────────────────────
detect_platform() {
  step 2 "Detecting platform..."

  OS="$(uname -s)"
  case "$OS" in
    Darwin)
      PLATFORM="macOS"
      MOBSF_DOCKER_HOST="host.docker.internal"
      ;;
    Linux)
      PLATFORM="Linux"
      # Docker's bridge gateway — reachable from inside any container
      MOBSF_DOCKER_HOST="172.17.0.1"
      ;;
    MINGW*|CYGWIN*|MSYS*)
      PLATFORM="Windows (Git Bash / WSL)"
      MOBSF_DOCKER_HOST="host.docker.internal"
      ;;
    *)
      PLATFORM="Unknown ($OS)"
      MOBSF_DOCKER_HOST="localhost"
      warn "Could not auto-detect platform. Defaulting MOBSF_DOCKER_HOST=localhost"
      ;;
  esac

  ok "Platform : $PLATFORM"
  ok "MOBSF_DOCKER_HOST : $MOBSF_DOCKER_HOST"
}

# ── Step 3 — Environment files ───────────────────────────────────────────────
setup_env_files() {
  step 3 "Setting up environment files..."

  # ── Root .env (docker compose variables) ──────────────────────────────────
  if [[ ! -f "${ROOT_DIR}/.env" ]]; then
    cat > "${ROOT_DIR}/.env" << EOF
# Auto-generated by setup.sh on $(date +%Y-%m-%d)
# Re-run ./setup.sh to regenerate, or edit manually.

# Platform-specific Docker host for MobSF container spawning
MOBSF_DOCKER_HOST=${MOBSF_DOCKER_HOST}

# Exposed host ports (change if these conflict with other services)
BACKEND_PORT=8000
MOBSF_PORT=5055
NODE_API_PORT=3000
FRONTEND_PORT=5500
EOF
    ok "Created .env"
  else
    # Just patch the MOBSF_DOCKER_HOST line in the existing file
    perl -i -pe "s|^MOBSF_DOCKER_HOST=.*|MOBSF_DOCKER_HOST=${MOBSF_DOCKER_HOST}|" "${ROOT_DIR}/.env"
    ok ".env already exists — updated MOBSF_DOCKER_HOST=${MOBSF_DOCKER_HOST}"
  fi

  # ── backend/.env ──────────────────────────────────────────────────────────
  if [[ -f "${ROOT_DIR}/backend/.env" ]]; then
    ok "backend/.env present (from repo)"
  else
    cp "${ROOT_DIR}/backend/.env.example" "${ROOT_DIR}/backend/.env"
    warn "backend/.env not found — created from template. Fill in credentials."
  fi

  # ── services/api/.env ─────────────────────────────────────────────────────
  if [[ -f "${ROOT_DIR}/services/api/.env" ]]; then
    ok "services/api/.env present (from repo)"
  else
    cp "${ROOT_DIR}/services/api/.env.example" "${ROOT_DIR}/services/api/.env"
    ok "Created services/api/.env from template"
  fi

  # ── services/worker/.env ──────────────────────────────────────────────────
  if [[ -f "${ROOT_DIR}/services/worker/.env" ]]; then
    ok "services/worker/.env present (from repo)"
  else
    cp "${ROOT_DIR}/services/worker/.env.example" "${ROOT_DIR}/services/worker/.env"
    ok "Created services/worker/.env from template"
  fi
}

# ── Step 4 — Data directories & SQLite files ─────────────────────────────────
setup_data() {
  step 4 "Initialising data directories..."

  # SQLite files must exist as files (not dirs) before Docker bind-mounts them
  touch "${ROOT_DIR}/backend/ingestion.db"
  touch "${ROOT_DIR}/backend/honeynet.db"
  ok "SQLite database files ready"

  mkdir -p "${ROOT_DIR}/backend/mobsf_service/data"
  ok "MobSF data directory ready"

  mkdir -p "${ROOT_DIR}/backend/scans"
  ok "Scan cache directory ready"
}

# ── Step 5 — Build & start ───────────────────────────────────────────────────
build_and_start() {
  step 5 "Building images and starting containers..."
  echo "  (First build may take 3–5 minutes — subsequent starts are instant)"
  echo ""
  cd "${ROOT_DIR}"
  ${COMPOSE_CMD} up --build -d
}

# ── Step 6 — Status & URLs ───────────────────────────────────────────────────
show_status() {
  step 6 "Verifying services..."
  sleep 4
  ${COMPOSE_CMD} ps

  # Read port overrides from .env if set
  BACKEND_PORT="${BACKEND_PORT:-8000}"
  MOBSF_PORT="${MOBSF_PORT:-5055}"
  NODE_API_PORT="${NODE_API_PORT:-3000}"
  FRONTEND_PORT="${FRONTEND_PORT:-5500}"

  echo ""
  echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}${BOLD}║   Shadow Trust is running!                           ║${NC}"
  echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "${BLUE}  Open in your browser:${NC}"
  echo -e "    Dashboard   →  ${CYAN}http://localhost:${FRONTEND_PORT}${NC}"
  echo -e "    API Docs    →  ${CYAN}http://localhost:${BACKEND_PORT}/docs${NC}"
  echo -e "    MobSF Svc  →  ${CYAN}http://localhost:${MOBSF_PORT}${NC}"
  echo -e "    Node API    →  ${CYAN}http://localhost:${NODE_API_PORT}${NC}"
  echo ""
  echo -e "${YELLOW}  Quick commands (or use make <target>):${NC}"
  echo "    make logs        ← tail all container logs"
  echo "    make status      ← show running containers"
  echo "    make restart     ← restart all services"
  echo "    make down        ← stop and remove containers"
  echo "    make rebuild     ← rebuild images + restart"
  echo "    make clean       ← stop + remove containers, images, volumes"
  echo ""
  echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────
banner
check_deps
detect_platform
setup_env_files
setup_data
build_and_start
show_status
